CATTY-378 Implemented AskBrick
Catrobat/Catty pull request #1480
Opened 2020-09-14 20:36 UTC by d4n3x

Implemented the AskBrick including some tests.

- [x] Include the name of the Jira ticket in the PR’s title
- [x] Verify that the Jira ticket is in the status *Ready for Development*
- [x] Include a summary of the changes plus the relevant context
- [ ] Choose the proper base branch (*develop*)
- [ ] Confirm that the changes follow the project’s coding guidelines
- [ ] Verify that the changes generate no compiler or linter warnings
- [ ] Perform a self-review of the changes
- [ ] Verify to commit no other files than the intentionally changed ones
- [ ] Include reasonable and readable tests verifying the added or changed behavior
- [ ] Confirm that new and existing unit tests pass locally
- [ ] Check that the commits’ message style matches the [project’s guideline](https://github.com/Catrobat/Catroid/wiki/Commit-Message-Guidelines)
- [ ] Stick to the project’s git workflow (rebase and squash your commits)
- [ ] Verify that your changes do not have any conflicts with the base branch
- [ ] After the PR, verify that all CI checks have passed
- [ ] Post a message in the *#catty* [Slack channel](https://catrobat.slack.com) and ask for a code reviewer

2020-09-15 07:42 UTC, aeluna requested changes
Thank you for the PR!
Please also include the new brick in the file ValidProjectAllBricks0992.xml.

2020-09-19 16:09 UTC, aeluna approved these changes

2020-09-29 05:14 UTC, m-herold requested changes
Thanks, looks good! I have added a few suggestions directly to the code. Here is one general problem:

When running for example this project (https://share.catrob.at/app/project/c91ddd8a-cb43-11ea-a5c3-005056a36f47) I have to click on the screen before the project continues after submitting an answer.

2020-09-29 05:14 UTC, m-herold commented on src/Catty/AskBrick+Instruction.swift
> +                         promptMessage: question.getDisplayString(),
Please remove the quotes from the alert message:

![Screenshot 2020-09-29 at 07 10 13](https://user-images.githubusercontent.com/6848980/94514976-d45de900-0222-11eb-95ba-3df715eb636a.png)

2020-09-29 05:18 UTC, m-herold requested changes
One more thing: please try to remove the "Cancel" button at the alert to be compliant with Catroid.

2020-10-11 10:31 UTC, m-herold requested changes

2020-10-11 10:31 UTC, m-herold commented on src/CattyTests/Bricks/AskBrickTests.swift
> +    func testAnswerNormal() {
Please provide another test case which documents that the value is not changing when submitting "" (no input).

2020-10-12 04:57 UTC, m-herold approved these changes

2020-10-12 05:00 UTC, m-herold commented
Thanks @d4n3x !

2020-10-12 05:00 UTC, merged