CATTY-415 Renamed Extensions for StagePresenterViewController
Catrobat/Catty pull request #1504
Opened 2020-10-14 10:39 UTC by zwerg4

Renamed ScenePresenterViewController+Resources.swift to StagePresenterViewControllerResourcesExtension.swift and
ScenePresenterViewController+Screenshot.swift to StagePresenterViewControllerScreenshotExtension.swift

### Your checklist for this pull request
Please review the [contributing guidelines](https://github.com/Catrobat/Catty/blob/develop/README.md) and [wiki pages](https://github.com/Catrobat/Catroid/wiki/) of this repository.

- [X] Include the name of the Jira ticket in the PR’s title
- [X] Verify that the Jira ticket is in the status *Ready for Development*
- [X] Include a summary of the changes plus the relevant context
- [X ] Choose the proper base branch (*develop*)
- [X] Confirm that the changes follow the project’s coding guidelines
- [X] Verify that the changes generate no compiler or linter warnings
- [X] Perform a self-review of the changes
- [X] Verify to commit no other files than the intentionally changed ones
- [ ] Include reasonable and readable tests verifying the added or changed behavior
- [X] Confirm that new and existing unit tests pass locally
- [X] Check that the commits’ message style matches the [project’s guideline](https://github.com/Catrobat/Catroid/wiki/Commit-Message-Guidelines)
- [X] Stick to the project’s git workflow (rebase and squash your commits)
- [X] Verify that your changes do not have any conflicts with the base branch
- [ ] After the PR, verify that all CI checks have passed
- [ ] Post a message in the *#catty* [Slack channel](https://catrobat.slack.com) and ask for a code reviewer

2020-10-14 11:09 UTC, m-herold requested changes
Please rename the files correctly (**StagePresenter**) and make sure that you include those changes in the project file.

2020-10-14 15:47 UTC, zwerg4 commented
Was my bad, I thought I should not include the project file because it gets generated when compiling.

2020-10-14 16:03 UTC, m-herold approved these changes

2020-10-16 06:51 UTC, merged

2020-10-16 06:51 UTC, m-herold commented
Thanks!