CATTY-285 Add tests for BrickFormulaProtocol 2/4
Catrobat/Catty pull request #1508
Opened 2020-10-19 12:51 UTC by zwerg4

Created new regression tests for the getFormulas method of the BrickFormulaProtocol. This is part 1 of 4, added test to following classes:
PhiroMotorMoveBackwardBrickTests (new class)
PhiroMotorMoveForwardBrickTests (new class)
PhiroPlayToneBrickTests (new class)
PhiroRGBLightBrickTests (new class)
ChangeTransparencyByNBrickTests
SayBubbleBrickTests (new class)
SayForBubbleBrickTests (new class)
SetBrightnessBrickTests
SetColorBrickTests
SetTransparencyToBrickTests

### Your checklist for this pull request
Please review the [contributing guidelines](https://github.com/Catrobat/Catty/blob/develop/README.md) and [wiki pages](https://github.com/Catrobat/Catroid/wiki/) of this repository.

- [X] Include the name of the Jira ticket in the PR’s title
- [X] Verify that the Jira ticket is in the status *Ready for Development*
- [X] Include a summary of the changes plus the relevant context
- [X] Choose the proper base branch (*develop*)
- [X] Confirm that the changes follow the project’s coding guidelines
- [X] Verify that the changes generate no compiler or linter warnings
- [X] Perform a self-review of the changes
- [X] Verify to commit no other files than the intentionally changed ones
- [X] Include reasonable and readable tests verifying the added or changed behavior
- [X] Confirm that new and existing unit tests pass locally
- [X] Check that the commits’ message style matches the [project’s guideline](https://github.com/Catrobat/Catroid/wiki/Commit-Message-Guidelines)
- [X] Stick to the project’s git workflow (rebase and squash your commits)
- [X] Verify that your changes do not have any conflicts with the base branch
- [ ] After the PR, verify that all CI checks have passed
- [ ] Post a message in the *#catty* [Slack channel](https://catrobat.slack.com) and ask for a code reviewer

2020-10-21 16:42 UTC, chrbesel approved these changes

2020-10-21 16:48 UTC, chrbesel commented
I have seen, you have got a merge conflict, you have to resolve it

2020-10-26 06:24 UTC, m-herold requested changes
Please resolve merge conflicts.

2020-10-26 17:52 UTC, m-herold approved these changes

2020-10-26 17:52 UTC, merged