CATTY-468: Create Stitch Brick
Catrobat/Catty pull request #1549
Opened 2020-12-03 15:07 UTC by Bomml

I created a small TestProgram. You can download it:
https://share.catrob.at/app/project/b365cb6d-327d-11eb-a92d-005056a36f47

### Your checklist for this pull request
Please review the [contributing guidelines](https://github.com/Catrobat/Catty/blob/develop/README.md) and [wiki pages](https://github.com/Catrobat/Catroid/wiki/) of this repository.

- [x] Include the name of the Jira ticket in the PR’s title
- [x] Verify that the Jira ticket is in the status *Ready for Development*
- [x] Include a summary of the changes plus the relevant context
- [x] Choose the proper base branch (*develop*)
- [x] Confirm that the changes follow the project’s coding guidelines
- [x] Verify that the changes generate no compiler or linter warnings
- [x] Perform a self-review of the changes
- [x] Verify to commit no other files than the intentionally changed ones
- [x] Include reasonable and readable tests verifying the added or changed behavior
- [x] Confirm that new and existing unit tests pass locally
- [x] Check that the commits’ message style matches the [project’s guideline](https://github.com/Catrobat/Catroid/wiki/Commit-Message-Guidelines)
- [x] Stick to the project’s git workflow (rebase and squash your commits)
- [x] Verify that your changes do not have any conflicts with the base branch
- [x] After the PR, verify that all CI checks have passed
- [x] Post a message in the *#catty* [Slack channel](https://catrobat.slack.com) and ask for a code reviewer

2020-12-19 10:18 UTC, aeluna approved these changes
Thank you for the PR!

2021-01-07 12:23 UTC, m-herold requested changes
Thanks for this great PR. I have left a few suggestions.

2021-01-07 12:23 UTC, m-herold commented on src/Catty/Defines/LanguageTranslationDefines.h
> +#define kLocalizedEmbroideryBricks NSLocalizedString(@"Use embroidery bricks", nil)
Please rename to "Embroidery extension". And add the following subtitle/description to the settings page:

> Create patterns for stitching machines

2021-01-07 12:23 UTC, m-herold commented on src/Catty/Setup/CatrobatSetup+Bricks.swift
> +        if isEmbroideryEnabled() {
If the embroidery extension is enabled, please add as first category (above "Event").

2021-02-06 08:10 UTC, m-herold approved these changes
Thanks!

2021-02-06 08:11 UTC, merged