CATTY-251 Extension for URLSession
Catrobat/Catty pull request #1555
Opened 2020-12-06 20:59 UTC by amelak9

Add an extension for the URLSession (Catty/Extensions.../Extensions/URLSessionMultipartExtension.swift) providing an multipart/form-data upload task:

open func multipartUploadTask(with url: URL, from formData: [String: String]?, attachmentData: [String: Data]?, completionHandler: @escaping (Data?, URLResponse?, Error?) -> Void) -> URLSessionUploadTask

- [ ] Include the name of the Jira ticket in the PR’s title
- [ ] Verify that the Jira ticket is in the status *Ready for Development*
- [ ] Include a summary of the changes plus the relevant context
- [ ] Choose the proper base branch (*develop*)
- [ ] Confirm that the changes follow the project’s coding guidelines
- [ ] Verify that the changes generate no compiler or linter warnings
- [ ] Perform a self-review of the changes
- [ ] Verify to commit no other files than the intentionally changed ones
- [ ] Include reasonable and readable tests verifying the added or changed behavior
- [ ] Confirm that new and existing unit tests pass locally
- [ ] Check that the commits’ message style matches the [project’s guideline](https://github.com/Catrobat/Catroid/wiki/Commit-Message-Guidelines)
- [ ] Stick to the project’s git workflow (rebase and squash your commits)
- [ ] Verify that your changes do not have any conflicts with the base branch
- [ ] After the PR, verify that all CI checks have passed
- [ ] Post a message in the *#catty* [Slack channel](https://catrobat.slack.com) and ask for a code reviewer

2020-12-08 13:54 UTC, KrennKristof approved these changes
looks good to me 👍

2020-12-11 17:14 UTC, m-herold requested changes
Thanks! I have left a few further suggestions. Please also use your method in the `StoreProjectUploader`.

2020-12-11 17:14 UTC, m-herold commented on src/CattyTests/URLSessionMultipartExtensionTests.swift
> +        self.project = Project()
Please make this test a unit test. This test should not and does not have to depend on a project, or on the `UserDefaults` or on a `FileManager`. Please test your method by simply verifying the header and body of your task (e.g., `task.originalRequest.allHTTPHeaderFields` and `task.originalRequest.httpBody` and `String(decoding: task.originalRequest!.httpBody!, as: UTF8.self)`).

2021-01-20 05:50 UTC, m-herold requested changes

2021-01-20 05:50 UTC, m-herold commented on src/Catty/Store/StoreProjectUploader.swift
> +        let url = URL(string: urlString)!
Please do not use force-unwrapping in production code. Use the completion handler to let the caller know that an error occurred (i.e., `.unexpectedError`).

2021-01-21 15:18 UTC, m-herold approved these changes

2021-01-21 15:18 UTC, merged