CATTY-459 Save changes in Paint
Catrobat/Catty pull request #1560
Opened 2020-12-22 00:43 UTC by amelak9

After drawing an image in Paint, the user is asked whether he/she wants to save the changes. This alert should appear BEFORE the view controller is changed, i.e. while still being in Paint. When the user presses "Cancel" then the user should still see the Paint with all his/her drawings

- [ ] Include the name of the Jira ticket in the PR’s title
- [ ] Verify that the Jira ticket is in the status *Ready for Development*
- [ ] Include a summary of the changes plus the relevant context
- [ ] Choose the proper base branch (*develop*)
- [ ] Confirm that the changes follow the project’s coding guidelines
- [ ] Verify that the changes generate no compiler or linter warnings
- [ ] Perform a self-review of the changes
- [ ] Verify to commit no other files than the intentionally changed ones
- [ ] Include reasonable and readable tests verifying the added or changed behavior
- [ ] Confirm that new and existing unit tests pass locally
- [ ] Check that the commits’ message style matches the [project’s guideline](https://github.com/Catrobat/Catroid/wiki/Commit-Message-Guidelines)
- [ ] Stick to the project’s git workflow (rebase and squash your commits)
- [ ] Verify that your changes do not have any conflicts with the base branch
- [ ] After the PR, verify that all CI checks have passed
- [ ] Post a message in the *#catty* [Slack channel](https://catrobat.slack.com) and ask for a code reviewer

2020-12-23 09:52 UTC, GatCode commented on fixDVRFixtures.txt
> +diff --git a/src/CattyTests/Store/Download/Fixtures/StoreProjectDownloader.fetchMostDownloadedProjects.IntegerId.success.json b/src/CattyTests/Store/Download/Fixtures/StoreProjectDownloader.fetchMost
please remove the fixDVRFixtures.txt file

2021-02-03 05:43 UTC, GatCode approved these changes

2021-02-04 12:16 UTC, m-herold requested changes

2021-02-04 12:16 UTC, m-herold commented on src/Catty/ViewController/Continue&New/MaintainObject/MaintainLooks/LooksTableViewController.m
> -- (void)showSavePaintImageAlert:(UIImage *)image andPath:(NSString *)path
`Class 'LooksTableViewController' does not conform to protocol 'PaintDelegate'`. Please change the delegate and remove unused methods.

2021-02-04 12:17 UTC, m-herold requested changes
When adding a look, saving to Pocket Code and cancelling the dialog where you have to enter a name, Catty crashes. Please add a regression test ensuring that this does not happen.

2021-02-10 18:51 UTC, m-herold requested changes

2021-02-10 18:51 UTC, m-herold commented on src/Catty/PocketPaint/ViewController/PaintViewController.m
> +                        [[UIApplication sharedApplication] openURL:[NSURL URLWithString:UIApplicationOpenSettingsURLString]];
This line gives a compiler warning:
`'openURL:' is deprecated: first deprecated in iOS 10.0`

Please bring back the initial `openURL` call (with `options` and `completionHandler` paramaters).

2021-02-10 18:51 UTC, m-herold commented on src/Catty/ViewController/Continue&New/MaintainObject/MaintainLooks/LooksTableViewController.m
> +        [[UIApplication sharedApplication] openURL:[NSURL URLWithString:UIApplicationOpenSettingsURLString]];
This line gives a compiler warning:
`'openURL:' is deprecated: first deprecated in iOS 10.0`

Please bring back the initial `openURL` call (with `options` and `completionHandler` paramaters).

2021-02-12 05:59 UTC, m-herold requested changes
With your changes, the following behavior has changed:
When not drawing at all (empty canvas or not making any changes to an existing image), then the alert is not still appearing, which was not the case before.

Please change that, so that again the alert is not being shown in those scenarios.

2021-02-15 14:49 UTC, m-herold approved these changes

2021-02-15 14:50 UTC, merged