CATTY-476 remove unused notification name defines, move used defines to NotificationExtension
Catrobat/Catty pull request #1578
Opened 2021-01-31 10:32 UTC by KrennKristof

removed unused Notification Defines and moved used Defines to Notification Extension

### Your checklist for this pull request
Please review the [contributing guidelines](https://github.com/Catrobat/Catty/blob/develop/README.md) and [wiki pages](https://github.com/Catrobat/Catroid/wiki/) of this repository.

- [ ] Include the name of the Jira ticket in the PR’s title
- [ ] Verify that the Jira ticket is in the status *Ready for Development*
- [ ] Include a summary of the changes plus the relevant context
- [ ] Choose the proper base branch (*develop*)
- [ ] Confirm that the changes follow the project’s coding guidelines
- [ ] Verify that the changes generate no compiler or linter warnings
- [ ] Perform a self-review of the changes
- [ ] Verify to commit no other files than the intentionally changed ones
- [ ] Include reasonable and readable tests verifying the added or changed behavior
- [ ] Confirm that new and existing unit tests pass locally
- [ ] Check that the commits’ message style matches the [project’s guideline](https://github.com/Catrobat/Catroid/wiki/Commit-Message-Guidelines)
- [ ] Stick to the project’s git workflow (rebase and squash your commits)
- [ ] Verify that your changes do not have any conflicts with the base branch
- [ ] After the PR, verify that all CI checks have passed
- [ ] Post a message in the *#catty* [Slack channel](https://catrobat.slack.com) and ask for a code reviewer

2021-01-31 20:51 UTC, amelak9 approved these changes

2021-02-02 06:42 UTC, m-herold requested changes

2021-02-02 06:42 UTC, m-herold commented on src/Catty/Extension&Delegate&Protocol/Extensions/NotificationExtension.swift
> +    public static let userInfoSound = "UserInfoSound"
This is not being used as a notification name, more like a key for the notification's user info. However, after looking at the removed and refactored notifications it seems like the following notifications are actually not in use anymore:

- `soundAdded` (including the user info and the never fired `soundAdded` method)
- `recordAdded`

2021-03-02 07:39 UTC, m-herold approved these changes

2021-03-02 07:40 UTC, merged