CATTY-526 Convert SetBrightnessBrick and ChangeBrightnessByNBrick to Swift
Catrobat/Catty pull request #1601
Opened 2021-02-23 22:00 UTC by amelak9

- [ ] Include the name of the Jira ticket in the PR’s title
- [ ] Verify that the Jira ticket is in the status *Ready for Development*
- [ ] Include a summary of the changes plus the relevant context
- [ ] Choose the proper base branch (*develop*)
- [ ] Confirm that the changes follow the project’s coding guidelines
- [ ] Verify that the changes generate no compiler or linter warnings
- [ ] Perform a self-review of the changes
- [ ] Verify to commit no other files than the intentionally changed ones
- [ ] Include reasonable and readable tests verifying the added or changed behavior
- [ ] Confirm that new and existing unit tests pass locally
- [ ] Check that the commits’ message style matches the [project’s guideline](https://github.com/Catrobat/Catroid/wiki/Commit-Message-Guidelines)
- [ ] Stick to the project’s git workflow (rebase and squash your commits)
- [ ] Verify that your changes do not have any conflicts with the base branch
- [ ] After the PR, verify that all CI checks have passed
- [ ] Post a message in the *#catty* [Slack channel](https://catrobat.slack.com) and ask for a code reviewer

2021-02-26 18:05 UTC, Bomml requested changes
You deleted the CBXMLHandler files. Please convert these files also to swift. They are needed to parse the project.

Please also convert the BrickCell files.

2021-02-26 18:05 UTC, Bomml commented on src/Catty/DataModel/Bricks/Look/ChangeBrightnessByNBrick.swift
> +    }
Do not force-unwrap here. guard let is a good option for example.

2021-02-26 18:05 UTC, Bomml commented on src/Catty/DataModel/Bricks/Look/SetBrightnessBrick.swift
> +        [brightness!]
Do not force-unwrap (like above)

2021-03-12 15:11 UTC, GatCode commented on src/Catty/DataModel/Bricks/Look/ChangeBrightnessByNBrick.swift
> +        self.changeBrightness
please add the missing return

2021-03-12 15:15 UTC, GatCode commented on src/Catty/DataModel/Bricks/Look/ChangeBrightnessByNBrick.swift
> +        [changeBrightness!]
return is missing and please don't use a force unwrap here - also maybe you can find a better solution for the [Formula]!

2021-03-12 15:15 UTC, GatCode commented on src/Catty/DataModel/Bricks/Look/ChangeBrightnessByNBrick.swift
> +        false
return is missing

2021-03-12 15:17 UTC, GatCode commented on src/Catty/DataModel/Bricks/Look/SetBrightnessBrick.swift
> +        kBrickCategoryType.lookBrick
returns also missing in that file

2021-03-12 15:18 UTC, GatCode commented on src/Catty/DataModel/Bricks/Look/SetBrightnessBrick.swift
> +        [brightness!]
please do not use the force unwrap here

2021-03-12 15:21 UTC, GatCode commented on src/Catty/Views/Custom/CollectionViewCells/BrickCells/Look/ChangeBrightnessByNBrickCell.swift
> +        CGFloat(kBrickHeight2h)
returns missing

2021-03-12 15:22 UTC, GatCode commented on src/Catty/Views/Custom/CollectionViewCells/BrickCells/Look/SetBrightnessBrickCell.swift
> +        CGFloat(kBrickHeight2h)
returns missing

2021-03-12 15:28 UTC, GatCode requested changes

2021-03-12 15:28 UTC, GatCode commented on src/Catty/DataModel/Bricks/Look/ChangeBrightnessByNBrick.swift
> +        self.changeBrightness
return is missing a lot of files - not only that one - please check all functions again

2021-03-12 15:28 UTC, GatCode commented on src/Catty/DataModel/Bricks/Look/ChangeBrightnessByNBrick.swift
> +        [changeBrightness!]
please avoid force unwrapping here - try to find a better solution - also with the [Formula]!

2021-03-12 15:28 UTC, GatCode commented on src/Catty/DataModel/Bricks/Look/SetBrightnessBrick.swift
> +        [brightness!]
please try to avoid it here too

2021-03-23 07:15 UTC, GatCode requested changes

2021-03-24 09:37 UTC, GatCode approved these changes

2021-04-06 10:52 UTC, m-herold commented
Thanks!

2021-04-06 10:52 UTC, merged