CATTY-522 Convert Util methods to Swift 1/3
Catrobat/Catty pull request #1610
Opened 2021-03-01 20:53 UTC by srinner

Convert the following methods of Util.m (and Util.h) to Util.swift:

- screenSize:
- screenHeight:
- screenWidth
- screenHeight
- screenWidth
- statusBarHeight

 Add tests to UtilTests.swift in case they do not exist yet.

### Your checklist for this pull request
Please review the [contributing guidelines](https://github.com/Catrobat/Catty/blob/develop/README.md) and [wiki pages](https://github.com/Catrobat/Catroid/wiki/) of this repository.

- [x] Include the name of the Jira ticket in the PR’s title
- [x] Verify that the Jira ticket is in the status *Ready for Development*
- [x] Include a summary of the changes plus the relevant context
- [x] Choose the proper base branch (*develop*)
- [x] Confirm that the changes follow the project’s coding guidelines
- [x] Verify that the changes generate no compiler or linter warnings
- [x] Perform a self-review of the changes
- [x] Verify to commit no other files than the intentionally changed ones
- [x] Include reasonable and readable tests verifying the added or changed behavior
- [x] Confirm that new and existing unit tests pass locally
- [x] Check that the commits’ message style matches the [project’s guideline](https://github.com/Catrobat/Catroid/wiki/Commit-Message-Guidelines)
- [x] Stick to the project’s git workflow (rebase and squash your commits)
- [x] Verify that your changes do not have any conflicts with the base branch
- [ ] After the PR, verify that all CI checks have passed
- [ ] Post a message in the *#catty* [Slack channel](https://catrobat.slack.com) and ask for a code reviewer

2021-03-03 13:14 UTC, zwerg4 requested changes

2021-03-03 13:14 UTC, zwerg4 commented on src/Catty/Helpers/Util/Util.swift
> +        if inPixel && UIScreen.main.bounds.height == CGFloat(kIphone6PScreenHeight) {
if you use kIphone6PScreenHeight you can delete "#define IS_IPHONEPLUS (([Util screenHeight] - kIphone6PScreenHeight) ? NO : YES)" in util.h

2021-03-03 13:44 UTC, zwerg4 approved these changes
looks good

2021-03-06 05:40 UTC, merged

2021-03-06 05:40 UTC, m-herold commented
Thanks!