CATTY-525 Convert SetLookBrick and SetBackgroundBrick to Swift
Catrobat/Catty pull request #1617
Opened 2021-03-05 16:23 UTC by Bomml

Convert SetLookBrick and SetBackgroundBrick (.m and .h) to Swift.

- [x] Include the name of the Jira ticket in the PR’s title
- [x] Verify that the Jira ticket is in the status *Ready for Development*
- [x] Include a summary of the changes plus the relevant context
- [x] Choose the proper base branch (*develop*)
- [x] Confirm that the changes follow the project’s coding guidelines
- [x] Verify that the changes generate no compiler or linter warnings
- [x] Perform a self-review of the changes
- [x] Verify to commit no other files than the intentionally changed ones
- [x] Include reasonable and readable tests verifying the added or changed behavior
- [x] Confirm that new and existing unit tests pass locally
- [x] Check that the commits’ message style matches the [project’s guideline](https://github.com/Catrobat/Catroid/wiki/Commit-Message-Guidelines)
- [x] Stick to the project’s git workflow (rebase and squash your commits)
- [x] Verify that your changes do not have any conflicts with the base branch
- [x] After the PR, verify that all CI checks have passed
- [x] Post a message in the *#catty* [Slack channel](https://catrobat.slack.com) and ask for a code reviewer

2021-03-10 14:36 UTC, aeluna approved these changes
Looks great!

2021-03-15 10:18 UTC, m-herold requested changes
Please see my suggestions and resolve merge conflicts. Thanks!

2021-03-15 10:18 UTC, m-herold commented on src/Catty/DataModel/Bricks/Look/SetBackgroundBrick.swift
> +    override func mutableCopy(with context: CBMutableCopyContext!) -> Any! {
Please remove force unwrapping of parameter and the guard, since it should never be called without a context.

2021-03-15 10:18 UTC, m-herold commented on src/Catty/DataModel/Bricks/Look/SetLookBrick.swift
> +@objcMembers class SetLookBrick: Brick, BrickLookProtocol {
Please see me suggestions for the `SetBackgroundBrick`, they basically also apply for this class here.

2021-03-17 11:17 UTC, m-herold approved these changes
Thanks!

2021-03-17 11:17 UTC, merged