CATTY-531 Store detail view landscape mode
Catrobat/Catty pull request #1627
Opened 2021-04-02 18:08 UTC by v15a1

* Changed data type of `descriptionLabel` to a UILabel
* Added constraints to resize the description to horizontal/vertical orientation width

- [ ] Include the name of the Jira ticket in the PR’s title
- [ ] Verify that the Jira ticket is in the status *Ready for Development*
- [ ] Include a summary of the changes plus the relevant context
- [ ] Choose the proper base branch (*develop*)
- [ ] Confirm that the changes follow the project’s coding guidelines
- [ ] Verify that the changes generate no compiler or linter warnings
- [ ] Perform a self-review of the changes
- [ ] Verify to commit no other files than the intentionally changed ones
- [ ] Include reasonable and readable tests verifying the added or changed behavior
- [ ] Confirm that new and existing unit tests pass locally
- [ ] Check that the commits’ message style matches the [project’s guideline](https://github.com/Catrobat/Catroid/wiki/Commit-Message-Guidelines)
- [ ] Stick to the project’s git workflow (rebase and squash your commits)
- [ ] Verify that your changes do not have any conflicts with the base branch
- [ ] After the PR, verify that all CI checks have passed
- [ ] Post a message in the *#catty* [Slack channel](https://catrobat.slack.com) and ask for a code reviewer

2021-04-03 04:42 UTC, m-herold requested changes
Constraints look good, however please change back to ```
`ActiveLabel` to support links (see CATTY-497).

2021-04-03 15:28 UTC, v15a1 commented
> Constraints look good, however please change back to 
> `ActiveLabel` to support links (see CATTY-497).

Will do!

2021-04-06 10:41 UTC, m-herold requested changes
Looks good, only one suggestions. Please squash your commits afterwards. Thanks a lot!

2021-04-06 10:41 UTC, m-herold commented on src/Catty/ViewController/Download/Details/ProjectDetailStoreViewControllerExtension.swift
> +            descriptionLabel.leadingAnchor.constraint(equalTo: view!.leadingAnchor, constant: (view?.frame.size.width ?? 0) / 15),
Please avoid force-unwrappings.

2021-04-08 06:51 UTC, m-herold requested changes

2021-04-08 06:51 UTC, m-herold commented on src/Catty/ViewController/Download/Details/ProjectDetailStoreViewControllerExtension.swift
> +    private func addProjectDescriptionLabel(withDescription description: String, to view: UIView!, target: Any?) -> CGFloat {
Please avoid force unwrappings.

2021-06-09 14:08 UTC, m-herold approved these changes
Thanks @v15a1!

2021-06-09 14:09 UTC, merged